using LiveKit.Proto;

namespace LiveKit
{
    /// <summary>
    /// Represents a chat message received in the room.
    /// </summary>
    public class ChatMessage
    {
        /// <summary>
        /// Unique identifier for the message.
        /// </summary>
        public string Id { get; }

        /// <summary>
        /// The timestamp when the message was sent.
        /// </summary>
        public long Timestamp { get; }

        /// <summary>
        /// The content of the message.
        /// </summary>
        public string Message { get; }

        /// <summary>
        /// Whether the message has been deleted.
        /// </summary>
        public bool Deleted { get; }

        /// <summary>
        /// Whether the message was generated by an AI agent.
        /// </summary>
        public bool Generated { get; }

        internal ChatMessage(Proto.ChatMessage proto)
        {
            Id = proto.Id;
            Timestamp = proto.Timestamp;
            Message = proto.Message;
            Deleted = proto.Deleted;
            Generated = proto.Generated;
        }
    }
}
